/* ─────────────────────────────────────────────────────────────
   living.js — the kit. One frame loop, one Point, one thread, one rail.

   Exposes:
     ASG.loop(el, step, resolve)     register on the one frame loop, visibility-gated
     ASG.sheet(kind, title, html)    the bottom sheet (what is this? · a vertebra · a code)
     ASG.roll(scope)                 the die — the honest pool is everything
     ASG.anchor(el|[x,y])            a figure lends the Point a place to be
     ASG.readable(hex, ground)       lift an accent until it is readable on this ground
     ASGfig.define(id, spec)         the figure contract (see figures/*.js)
     ASGfig.mount()                  mount every registered figure into [data-fig]

   CONTRACT RULE — a figure's css must not collide with the kit or another figure:
   scope every selector under [data-fig="<id>"] or prefix its class names. (The door's
   .dn span and the dances' .dn host once collided; the doors inherited aspect-ratio:1.)

   Data: the WORLDS / SPINE blocks below are generated by Claude Code from
   data/worlds.json + data/spine.json between the @worlds markers. Nothing else
   in this file is generated. Counts come from the register, never from a literal.
   ───────────────────────────────────────────────────────────── */
(function(){
var $=function(id){return document.getElementById(id)};
var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
var DPR=Math.min(2,window.devicePixelRatio||1);

/* ── one heartbeat for every moving thing ── */
var LOOPS=[],raf=0;
/* ── and one place that keeps IntersectionObservers alive ──
   Firefox collects an observer nothing holds a reference to, so every observer
   this site makes is retained here. Figures must use api.watch, never `new
   IntersectionObserver(...).observe(el)` inside a mount that then returns. */
var OBS=[];
function watch(el,fn,opts){
  if(!('IntersectionObserver' in window))return null;
  var o=new IntersectionObserver(fn,opts||{threshold:[0,.45,.8]});
  o.observe(el);OBS.push(o);return o}
function loop(el,fn,still){LOOPS.push({el:el,fn:fn,still:still,was:false});if(VIO)VIO.observe(el);setTimeout(kick,0)}
function vis(el){var r=el.getBoundingClientRect();return r.height>0&&r.bottom>-120&&r.top<innerHeight+120}
/* the per-frame loop asks "is it on screen?" of every figure, every frame. An IntersectionObserver answers that
   once, when it changes (the same 120px margin), so tick() reads a flag instead of forcing layout per figure per
   frame. Only tick() uses it: it runs in the same rendering step the observer does, so the flag is never stale
   there. pump() and the reduced-motion path keep the exact read — they must work from scroll alone (see pump). */
var VIS=typeof WeakMap!=='undefined'?new WeakMap():null,
    VIO=VIS&&window.IntersectionObserver?new IntersectionObserver(function(es){var woke=false;
      es.forEach(function(e){var v=e.isIntersecting&&e.boundingClientRect.height>0;if(v&&!VIS.get(e.target))woke=true;VIS.set(e.target,v)});
      if(woke)kick()},{rootMargin:'120px 0px'}):null;
function visf(el){return VIO&&VIS.has(el)?VIS.get(el):vis(el)}
function kick(){if(reduced){LOOPS.forEach(function(o){var v=vis(o.el);if(v&&!o.was&&o.still)o.still();o.was=v});return}
  /* always reschedule from scratch: holding a stale raf id here deadlocked the
     whole frame loop whenever a scheduled frame never fired (a backgrounded
     iframe, a long task), and every moving thing on the page stopped for good. */
  if(raf)cancelAnimationFrame(raf);
  raf=requestAnimationFrame(tick)}
function tick(t){raf=0;var any=false;
  for(var i=0;i<LOOPS.length;i++){var o=LOOPS[i];
    if(!document.hidden&&visf(o.el)){
      /* one throwing step used to abort tick() for every loop on the page and
         stop the whole site until reload. A fault is now isolated to its own
         step, retired, and named on <html data-loop-fail>. */
      try{o.fn(t)}catch(e){
        o.fn=function(){};
        var m=document.documentElement.getAttribute('data-loop-fail')||'';
        document.documentElement.setAttribute('data-loop-fail',
          m+(m?' | ':'')+((o.el&&o.el.id)||'?')+': '+(e&&e.message||e))}
      any=true}}
  if(any)raf=requestAnimationFrame(tick)}
addEventListener('scroll',function(){kick();pump()},{passive:true});
addEventListener('resize',function(){kick();pump()});
document.addEventListener('visibilitychange',kick);
/* Scroll-driven state must never depend on requestAnimationFrame. rAF is
   throttled to nothing in an unpainted frame (a background tab, an offscreen
   iframe, a screenshot harness), and anything that only advanced on rAF simply
   never happened there. pump() runs every registered step once per scroll, so
   state lands from scroll alone; rAF remains for per-frame motion on top. */
var pumping=false;
function pump(){
  if(pumping||reduced)return;pumping=true;
  var t=(window.performance&&performance.now())||Date.now();
  for(var i=0;i<LOOPS.length;i++){var o=LOOPS[i];
    if(vis(o.el)){try{o.fn(t)}catch(e){o.fn=function(){}}}}
  pumping=false}
function fitc(cv){var w=cv.clientWidth,h=cv.clientHeight;
  if(cv.width!==Math.round(w*DPR)||cv.height!==Math.round(h*DPR)){
    cv.width=Math.round(w*DPR);cv.height=Math.round(h*DPR)}
  var x=cv.getContext('2d');x.setTransform(DPR,0,0,DPR,0,0);return x}

/* ── readable(): accents lift on dark grounds ── */
function hex(c){c=c.replace('#','');if(c.length===3)c=c[0]+c[0]+c[1]+c[1]+c[2]+c[2];
  return [parseInt(c.slice(0,2),16),parseInt(c.slice(2,4),16),parseInt(c.slice(4,6),16)]}
function lum(c){var r=hex(c).map(function(v){v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)});
  return .2126*r[0]+.7152*r[1]+.0722*r[2]}
function readable(c,ground){var g=lum(ground||'#0B0910'),k=0,r=hex(c);
  while(k<24){var l=lum('#'+r.map(function(v){return ('0'+v.toString(16)).slice(-2)}).join(''));
    var hi=Math.max(l,g)+.05,lo=Math.min(l,g)+.05;
    if(hi/lo>=4.5)break;
    r=r.map(function(v){return Math.min(255,Math.round(v+(255-v)*.12))});k++}
  return '#'+r.map(function(v){return ('0'+v.toString(16)).slice(-2)}).join('')}

/* ═══ @worlds — generated by learning-register/tools/v3/blocks.py from the world table (docs/v3/world-table.json) + spine.json. The same pass writes thread.js @spine. ═══ */
var VNAMES=["","Bindu","Muladhara","Svadhisthana","Manipura","Anahata","Vishuddha","Ajna","Sahasrara","Shadow","Soles","Forge","Prana","Hands","Pulse","Sonar","Echo","Vision","Axis","Crow","Armin","Inception","Intention","Inspiration","Insight","Intuition","Invention","Incarnation","Innocence","Integration","Maya","Aatma","Ego Reveal","Lalita"];
var VCOL=["","#C9A84C","#B33A2E","#D8742A","#D9B531","#6B8E4E","#3A7CA5","#3F3A8A","#6A3D8A","#1B1730","#B33A2E","#D9B531","#D8742A","#6B8E4E","#6B8E4E","#3A7CA5","#3A7CA5","#D9B531","#1A0848","#6A3D8A","#7BB661","#2D2458","#3A3670","#3A4880","#403875","#453870","#4A3368","#522D60","#5A2858","#5E2448","#5A3D8A","#D4A948","#3D6B35","#C9A84C"];
var BANDS={E:[2,8],B:[10,19],M:[21,29],R:[1,9,20,30,31,32,33],all:[1,33]};
/* id, name, movement, vertebra | [vertebrae] | band, accent, built-on-this-page */
var WORLDS=[
 ["walk","The Walk","II","all","#D9B45A",1],
 ["chakramap","The Chakra Map","II","all","#D9B45A",1],
 ["practicebook","The Practice Book","II","all","#D9B45A",1],
 ["dances","The Dances","II","B","#E8866A",1],
 ["readings","The Readings","II","E","#7FC0CF",1],
 ["teachings","The Teachings","II","M","#B9A2EC",1],
 ["learning","Learning","II","M","#8FAEEE",1],
 ["courses","The Courses","II","B","#8FAEEE",1],
 ["guidebook","The Guidebook","II","R","#9CC48A",1],
 ["forms","The Forms","II",26,"#9CC48A",1],
 ["story","A Strange Story","III",[27,28,29],"#E39473",1],
 ["voice","A Strange Voice","III","B","#E7A0B6",1],
 ["game","A Strange Game","III","all","#C9A84C",1],
 ["voicelibrary","The Voice Library","III",6,"#7FC0CF",1],
 ["tree","The Tree of Life","IV",[2,3,4,5,6,7,8,30,31],"#B33A2E",1],
 ["axis","The Axis","IV",18,"#8FA8E8",1],
 ["threetrees","The Three Trees","IV","all","#A9D097",1],
 ["templeguide","The Temple Guide","IV",31,"#D4A948",1],
 ["feed","Bindu Feed","V",1,"#F0705A",1],
 ["learningapp","Bindu Learning","V","M","#9CB8F2",1],
 ["voiceapp","Bindu Voice","V",15,"#6FB6DE",1],
 ["fieldapp","Bindu Field","V",16,"#8FCBD8",1],
 ["being","Bindu Being","V",24,"#A79DE8",1],
 ["lalitafamily","Lalita Family","V",33,"#EDC28A",1],
 ["mandala","Bindu Mandala","V",1,"#DCB05A",1],
 ["chakrasapp","Bindu Chakras","V","all","#D4836A",1],
 ["bindu","Bindu","VI",1,"#D4553F",1],
 ["gaia","Gaia","VI",10,"#7FA86B",1],
 ["sid","Sid","VI",11,"#9BBDE4",1],
 ["arch","Arch","VI",6,"#E6A8BC",1],
 ["sakshi","Sakshi","VI",18,"#E8DED4",1],
 ["karishma","Karishma","VI",28,"#E8A0B6",1],
 ["neev","Neev","VI",2,"#93A3B4",1],
 ["shweta","Shweta","VI",3,"#EFE7D9",1],
 ["ashrey","Ashrey","VI",31,"#D4A948",1],
 ["lalita","Lalita","VI",33,"#C9A84C",1],
 ["thefield","The Field","VII",1,"#E0492F",1],
 ["registers","The Registers","VII","all","#12A06E",1],
 ["temporal","The Temporal","VII",28,"#EFA110",1],
 ["codex","The Codex","VII",9,"#4A48C8",1],
 ["reveals","The Reveals","VII",32,"#C83BB4",1],
 ["elements","The Elements","VII",18,"#1596C9",1],
 ["mirror","The Mirror","VIII",18,"#8FB073",1],
 ["plays","The Plays","VIII",33,"#CFD8DE",1],
 ["selfgenerator","A Self Generator","VIII",31,"#8FB073",1],
 ["lucky","It Was Always Lucky","IX",11,"#D9B45A",1],
 ["holi","Khelo Holi","IX",13,"#FFB35C",1],
 ["moments","The Moments","IX","all","#C9A06A",1]
];
/* ═══ @end ═══ */
/* ═══ @now — the Now line, self-ageing (v2; 03-THE-LIVING-KIT). Generated from data/now.json:
   every entry carries `at` and `until`, so the line says what is new on its own and goes quiet
   on its own date. v3 had shipped it as a typed string, which would have announced the walk
   forever. The markup keeps that string as the no-JS fallback. ═══ */
var NOW=[{"at":"2026-09-26","until":"2026-11-15","t":"The house is rebuilt","s":"forty-eight worlds, one spine","h":"/spine/"},{"at":"2026-09-26","until":"2026-11-15","t":"Three lakes of learning","s":"therapy, consciousness, learning","h":"/learning/"},{"at":"2026-09-26","until":"2026-11-15","t":"Every belief, in the Codex","s":"what each one built, first","h":"/worlds/codex/"}];
/* ═══ @end ═══ */
/* D12 · registered but not live yet (generated ASG_ARRIVING): never a link, always "arriving" */
function arriving(h){if(!h||h.charAt(0)!=='/')return false;var A=window.ASG_ARRIVING||[],p=h.split('#')[0];
  return A.indexOf(p)>=0}
function nowLine(){
  var a=document.getElementById('now');if(!a)return;
  var d=new Date(),today=d.getFullYear()+'-'+('0'+(d.getMonth()+1)).slice(-2)+'-'+('0'+d.getDate()).slice(-2);
  /* a Now entry whose page isn't live yet stays quiet until it is: the line never points at nothing */
  var cur=NOW.filter(function(n){return n.at<=today&&today<n.until&&!arriving(n.h)})[0];
  if(!cur){a.style.display='none';a.setAttribute('aria-hidden','true');return}
  a.href=cur.h;var s=a.querySelector('span');if(s)s.textContent=cur.t+(cur.s?' \u2014 '+cur.s:'')+'.'}
var BY={};WORLDS.forEach(function(w){BY[w[0]]={nm:w[1],mv:w[2],p:w[3],c:w[4],built:!!w[5]}});
/* A world's key is not its element id — the movements prefix theirs (v- g- c- d-).
   Every section carries data-world, so resolve the anchor, never assume it. */
function node(id){return document.querySelector('[data-world="'+id+'"]')}
function href(id){var n=node(id);return n&&n.id?'#'+n.id:null}
function goTo(id){var a=href(id);if(a)location.hash=a;return !!a}
function vlist(p){if(typeof p==='number')return [p];if(Array.isArray(p))return p;
  var b=BANDS[p];if(!b)return [];if(p==='R')return b.slice();
  var o=[];for(var n=b[0];n<=b[1];n++)o.push(n);return o}

/* ═══ the figure contract ═══ */
var FIGS={},CSSDONE={};
var ASGfig={
  define:function(id,spec){spec.id=id;FIGS[id]=spec},
  get:function(id){return FIGS[id]},
  all:function(){return FIGS},
  /* every [data-fig] host gets its figure: css once, then mount, then step on the one loop */
  mount:function(){
    document.querySelectorAll('[data-fig]').forEach(function(host){
      var id=host.dataset.fig,f=FIGS[id];
      if(!f){host.setAttribute('data-gap','no figure registered for '+id);return}
      if(f.css&&!CSSDONE[id]){CSSDONE[id]=1;
        var s=document.createElement('style');s.textContent=f.css;document.head.appendChild(s)}
      var api={lens:ASGlens.get(),readable:readable,fitc:fitc,reduced:reduced,
        sheet:sheet,anchor:anchor,register:REG,vname:function(n){return VNAMES[n]},
        vcol:function(n){return VCOL[n]},world:BY[id]||{},watch:watch,
        loop:function(fn,still){loop(host,fn,still)}};
      try{f.mount(host,api)}catch(e){host.setAttribute('data-gap',String(e&&e.message||e))}
      if(f.words&&!host.getAttribute('aria-label'))host.setAttribute('aria-label',f.words());
      if(f.step)loop(host,function(t){f.step(t,api)},function(){f.resolve&&f.resolve(host,api)});
      else if(reduced&&f.resolve)f.resolve(host,api);
    })}
};

/* one door per place: a doors-row pill that goes where the world's own figure already offers to go
   (the Chakra Map's "Open the map") is hidden once the figure is drawn — without script the figure
   isn't there, and the row keeps it */
function oneDoor(){
  [].forEach.call(document.querySelectorAll('[data-block=doors]'),function(r){
    var s=r.closest('section');if(!s)return;
    [].forEach.call(r.querySelectorAll('a.pill[href]'),function(a){
      if(/^go in/.test(a.textContent.trim()))return;
      var h=a.getAttribute('href'),dup=[].some.call(s.querySelectorAll('a[href]'),function(b){
        return b!==a&&!r.contains(b)&&b.getAttribute('href')===h});
      if(dup)a.hidden=true})})}

/* ═══ the register — grows behind a world, never as a world ═══ */
var REG={
  entries:(window.ASG_REGISTER||[]),
  of:function(world){return REG.entries.filter(function(e){return e.w===world})},
  count:function(world,st){return REG.entries.filter(function(e){
    return e.w===world&&(!st||e.st===st)}).length},
  kinds:function(k){return REG.entries.filter(function(e){return e.k===k})}
};

/* ═══ the sheet ═══ */
function sheet(kind,title,body){
  $('shK').textContent=kind;$('shT').textContent=title;$('shB').innerHTML=body;
  $('sheet').classList.add('on');$('sheet').setAttribute('aria-hidden','false')}
function closeSheet(){$('sheet').classList.remove('on');$('sheet').setAttribute('aria-hidden','true')}

/* ═══ the Constellation — April's all-worlds menu (harvest round four) ═══
   Every world, grouped by its movement, in the page's own order, the one you are in lit.
   One tap goes: a NAME is a door (the Sky's two-tap law is for unnamed lights). Built from
   WORLDS + the DOM each time it opens, so it can never disagree with the page. */
var CST=null,cstBack=null;
function cstEsc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;')}
function cstBuild(){
  var ord=zones.filter(function(q){return BY[q.dataset.world]}),num={};
  ord.forEach(function(q,i){num[q.dataset.world]=i+1});
  var mv=[],MN={};
  [].forEach.call(document.querySelectorAll('.seam[data-movement]'),function(s){
    var t=s.querySelector('.mt');MN[s.dataset.movement]=t?t.textContent.trim():''});
  ord.forEach(function(q){var m=BY[q.dataset.world].mv;if(mv.indexOf(m)<0)mv.push(m)});
  var h='<button class="cx" type="button" aria-label="Close">\u00d7</button><div class="cst-in">'+
    '<p class="cst-k">The Constellation</p>'+
    '<h2 class="cst-t">'+spellN(ord.length)+' worlds. Touch a name and you are there.</h2>'+
    '<div class="cst-top"><a href="#sky" data-to="sky">the Sky \u2014 the spine, seen whole</a>'+
    '<a href="#threshold" data-to="threshold">the doors</a>'+
    (arriving('/tab-menu')?'<span class="rc-arr" aria-disabled="true">every page, by name <small>arriving</small></span>'
      :'<a href="/tab-menu">every page, by name \u2192</a>')+'</div><div class="cst-g">';
  mv.forEach(function(m){
    var ws=ord.filter(function(q){return BY[q.dataset.world].mv===m}),c=BY[ws[0].dataset.world].c;
    h+='<section class="cst-m" style="--m:'+c+';--mt:'+readable(c,'#0B0910')+'"><h3><b>'+m+'</b><span>'+
      cstEsc(MN[m]||'')+'</span><i>'+ws.length+'</i></h3><svg aria-hidden="true"><path/></svg><ol>'+
      ws.map(function(q,i){var id=q.dataset.world,w=BY[id];
        return '<li style="--dy:'+(Math.sin(i*1.9+m.length)*5).toFixed(1)+'px"><a href="#'+q.id+'" data-to="'+id+
          '" style="--p:'+readable(w.c,'#0B0910')+'"><i></i><u>'+('0'+num[id]).slice(-2)+'</u><span>'+
          cstEsc(w.nm)+'</span></a></li>'}).join('')+'</ol></section>'});
  h+='</div><p class="cst-foot">The only winning move is to play.</p></div>';
  CST.innerHTML=h;
  CST.querySelector('.cx').addEventListener('click',cstClose);
  [].forEach.call(CST.querySelectorAll('[data-to]'),function(a){a.addEventListener('click',function(e){
    e.preventDefault();var to=a.dataset.to;cstClose(true);
    var n=to==='sky'||to==='threshold'?document.getElementById(to):node(to);
    if(n&&n.id)location.hash='#'+n.id})})}
function spellN(n){var W=['','one','two','three','four','five','six','seven','eight','nine'],
  T={40:'Forty',50:'Fifty',30:'Thirty',20:'Twenty'},t=Math.floor(n/10)*10,u=n%10;
  return T[t]?T[t]+(u?'-'+W[u]:''):String(n)}
/* the thread between the stars of each movement, drawn once the names have laid out */
function cstThreads(){
  [].forEach.call(CST.querySelectorAll('.cst-m'),function(m){
    var b=m.getBoundingClientRect(),d='';
    [].forEach.call(m.querySelectorAll('a i'),function(i,k){var r=i.getBoundingClientRect();
      d+=(k?'L':'M')+(r.left-b.left+r.width/2).toFixed(1)+' '+(r.top-b.top+r.height/2).toFixed(1)});
    var sv=m.querySelector('svg');sv.setAttribute('viewBox','0 0 '+b.width.toFixed(0)+' '+b.height.toFixed(0));
    sv.querySelector('path').setAttribute('d',d)})}
function cstOpen(){
  if(!CST){CST=document.createElement('div');CST.id='cst';CST.setAttribute('role','dialog');
    CST.setAttribute('aria-modal','true');CST.setAttribute('aria-label','The Constellation \u2014 every world');
    CST.hidden=true;document.body.appendChild(CST);
    CST.addEventListener('keydown',function(e){e.stopPropagation();
      if(e.key==='Escape')cstClose();
      else if(e.key==='Tab'){var f=[].slice.call(CST.querySelectorAll('a,button')),k=f.indexOf(document.activeElement);
        if(e.shiftKey&&k<=0){e.preventDefault();f[f.length-1].focus()}
        else if(!e.shiftKey&&k===f.length-1){e.preventDefault();f[0].focus()}}});
    addEventListener('resize',function(){if(CST&&!CST.hidden)cstThreads()})}
  cstBack=document.activeElement;cstBuild();CST.hidden=false;
  document.documentElement.style.overflow='hidden';
  var here=CST.querySelector('[data-to="'+cur+'"]');if(here)here.classList.add('here');
  cstThreads();setTimeout(function(){CST.classList.add('on')},20);
  (here||CST.querySelector('.cx')).focus({preventScroll:true});
  if(here){var r=here.getBoundingClientRect();if(r.bottom>innerHeight-40)CST.scrollTop+=r.top-innerHeight/2}}
function cstClose(going){if(!CST)return;CST.classList.remove('on');CST.hidden=true;
  document.documentElement.style.overflow='';
  if(!going&&cstBack&&cstBack.focus)cstBack.focus({preventScroll:true})}
window.ASGconstellation={open:cstOpen,close:cstClose};

/* ═══ the die — the honest pool is everything ═══ */
function roll(scope){
  var pool=WORLDS.filter(function(w){return w[5]});
  var pick=pool.length?pool[(Math.random()*pool.length)|0]:null;
  var d=$('die');if(d)d.classList.add('filled');
  if(!pick){sheet('the die','Nothing is built here yet','<p>Honest pool, honest answer.</p>');return}
  sheet('the field chose',pick[1],
    (scope&&BY[scope]?'<p style="color:rgba(245,239,230,.66)">Rolled from inside '+BY[scope].nm+'.</p>':'')+
    '<p style="color:rgba(245,239,230,.66)">The pool is everything — '+WORLDS.length+
    ' worlds and every page behind them. '+
    'It can only land where a world is built.</p><ul><li><a href="'+(href(pick[0])||'#threshold')+'">go there \u2192</a></li></ul>')}

/* ═══ the Point — one element, created once, never replaced ═══ */
var pt,pt2,ily,ANCH=null,marks=[],markI=0;
var P={x:0,y:0,state:'threshold',born:false,split:false};
function threadX(){return parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--thread-x'))||20}
function anchor(a){ANCH=a}
function target(){
  var st=P.state;
  if(st==='threshold'){var r=$('idot').getBoundingClientRect();return [r.left+r.width/2,r.top+r.height/2]}
  if(st==='anchor'&&ANCH){
    if(ANCH.getBoundingClientRect){var b=ANCH.getBoundingClientRect();
      if(b.width)return [b.left+b.width/2,b.top+b.height/2]}
    else if(ANCH.length)return ANCH}
  if(st==='centre')return [innerWidth*.5,clearY(innerHeight*.5)];
  if(st==='sky'){var s=$('skymap');if(s){var q=s.getBoundingClientRect();return [q.left+q.width*.5,q.top+q.height*.5]}}
  return [threadX(),innerHeight*.5]}
/* VI · the Point goes to the centre of the screen — and rests in the gap nearest the centre, never on
   a word (it sat on "every yard." in Sid's line, and on every vantage's centred sentence). The world's
   words are read once per world; the gap is found from their boxes, a handful per frame. */
var CLR=null,CLRz=null;
function clearY(y){
  if(CLRz!==curZ){CLRz=curZ;CLR=curZ?[].slice.call(curZ.querySelectorAll('p,h2,h3,h4,.wt,.we,.moment,.said,.who,.g-q,.g-s,.row,.pill,em,.mk,.mark')):[]}
  var cx=innerWidth*.5,hits=[];
  for(var i=0;i<CLR.length;i++){var r=CLR[i].getBoundingClientRect();
    if(r.height&&r.left-8<cx&&r.right+8>cx&&r.bottom>0&&r.top<innerHeight)hits.push(r)}
  for(var k=0;k<6;k++){var on=null;
    for(var j=0;j<hits.length;j++)if(y>hits[j].top-10&&y<hits[j].bottom+10){on=hits[j];break}
    if(!on)return y;
    y=(y-(on.top-10)<(on.bottom+10)-y)?on.top-12:on.bottom+12}
  return y}
function pointStep(){
  var t=target(),L=ASGlens.get();
  P.x+=(t[0]-P.x)*L.ease;P.y+=(t[1]-P.y)*L.ease;
  pt.style.transform='translate('+(P.x-4.5)+'px,'+(P.y-4.5)+'px)';
  if(P.split)pt2.style.transform='translate('+(innerWidth-16)+'px,'+(P.y+64)+'px)';
  var w=L.point==='source'?13:L.point==='character'?11:9;
  pt.style.width=pt.style.height=w+'px'}
function birth(on){
  if(on&&!P.born){P.born=true;$('iEl').classList.add('departed');pt.classList.remove('hid');
    var r=$('idot').getBoundingClientRect();P.x=r.left+r.width/2;P.y=r.top+r.height/2}
  else if(!on&&P.born){P.born=false;$('iEl').classList.remove('departed');pt.classList.add('hid')}}
function dropMark(){if(ASGlens.get().point!=='witnessed'||!marks.length)return;
  var m=marks[markI++%marks.length];m.style.transform='translate('+(P.x-2.5)+'px,'+(P.y-2.5)+'px)'}

/* ═══ the thread — sewn only where the Point has passed; it begins where the Point is born ═══ */
var strand,stitch,clipR=null,SEW_OFF=0,SEW_H=0,sewFreeze=null;
function sew(){
  var desc=$('descent');if(!desc||!strand)return;
  SEW_OFF=desc.offsetTop+Math.round(desc.offsetHeight*.44);
  SEW_H=Math.max(0,document.documentElement.scrollHeight-SEW_OFF);
  var tx=threadX(),d='',k='';
  for(var y=0;y<=SEW_H;y+=16){var x=tx+Math.sin((y+SEW_OFF)*.013)*1.2+Math.sin((y+SEW_OFF)*.047+1)*.7;
    d+=(y?'L':'M')+x.toFixed(1)+' '+y}
  document.querySelectorAll('.world .wh .bead').forEach(function(b){
    var r=b.getBoundingClientRect(),y=r.top+r.height/2+scrollY-SEW_OFF;
    if(y<0||y>SEW_H)return;
    k+='M'+(tx-4)+' '+(y-4)+' l8 8 m0 -8 l-8 8 '});
  strand.style.top=SEW_OFF+'px';strand.style.height=SEW_H+'px';
  stitch.setAttribute('viewBox','0 0 44 '+SEW_H);stitch.style.height=SEW_H+'px';
  stitch.innerHTML='<defs><clipPath id="sewn"><rect x="-20" y="0" width="90" height="0"/></clipPath></defs>'+
    '<g clip-path="url(#sewn)" class="ink"><path class="sh" d="'+d+'"/><path d="'+d+'"/><path d="'+k+'"/></g>';
  clipR=stitch.querySelector('rect');
  var un=$('unsewn');if(un)un.style.left=(tx-.6)+'px';
  sewScroll()}
function sewNow(){sewQ=0;if(!clipR)return;
  var head=scrollY+innerHeight*.5-SEW_OFF;
  if(sewFreeze!==null)head=Math.min(head,sewFreeze-SEW_OFF);
  clipR.setAttribute('height',Math.max(0,reduced?1e6:head))}
/* the thread is MOTION, so its write waits for the next frame: written straight from the scroll
   event it dirtied the page's layout before every loop's read (vis(), pickWorld), and each scroll
   paid a forced synchronous layout of the whole page — the heaviest thing on a throttled phone.
   A timer backs the frame up, so an unpainted frame still gets its thread. */
var sewQ=0;
function sewScroll(){if(sewQ)return;sewQ=1;requestAnimationFrame(sewNow);setTimeout(function(){if(sewQ)sewNow()},120)}
addEventListener('scroll',sewScroll,{passive:true});

/* ═══ the spine rail ═══ */
var railEls=[];
function drawRail(){var mode=ASGlens.get().rail;
  railEls.forEach(function(el,i){var n=i+1;
    if(mode==='colour-thread'){el.style.background=el.classList.contains('ring')?'':VCOL[n];el.style.opacity=.6}
    else if(mode==='five-mark'){el.style.background='';el.style.opacity=.85;el.style.width=(n%11===0?15:9)+'px'}
    else{el.style.background='';el.style.opacity='';el.style.width=''}})}
function railSheet(n){
  var here=WORLDS.filter(function(w){return vlist(w[3]).indexOf(n)>=0});
  var anch=here.filter(function(w){return typeof w[3]==='number'||Array.isArray(w[3])});
  var rest=here.filter(function(w){return anch.indexOf(w)<0});
  var li=anch.concat(rest).map(function(w){
    var a=w[5]&&href(w[0]);
    return '<li>'+(a?'<a href="'+a+'">':'<button type="button" data-soon="'+w[1]+'">')+w[1]+
      '<span style="float:right;opacity:.55;font-size:12px">'+w[2]+(w[5]?'':' \u00b7 not on this page yet')+
      '</span>'+(a?'</a>':'</button>')+'</li>'}).join('');
  sheet('vertebra '+n,VNAMES[n],'<p style="color:rgba(245,239,230,.66)">'+
    (anch.length?anch.length+' world'+(anch.length>1?'s stand':' stands')+' here.'
      :'No world of its own yet \u2014 only the walk has reached this one so far. Room, not a gap.')+
    '</p><ul>'+li+'</ul>');
  $('shB').querySelectorAll('[data-soon]').forEach(function(b){b.addEventListener('click',function(){
    sheet('still to come',b.dataset.soon,'<p>Specified and positioned. It arrives with its movement.</p>')})})}
function spineSheet(){
  var z=curZ&&curZ.dataset.v,here={};
  if(z==='all'){for(var i=1;i<=33;i++)here[i]=1}else if(z)z.split(',').forEach(function(n){here[+n]=1});
  var rows='';
  for(var n=1;n<=33;n++){
    var c=WORLDS.filter(function(w){return vlist(w[3]).indexOf(n)>=0&&
      (typeof w[3]==='number'||Array.isArray(w[3]))}).length;
    rows+='<li><button type="button" data-n="'+n+'"'+(here[n]?' style="color:var(--ac)"':'')+'>'+
      '<span style="display:inline-block;width:2.2em;opacity:.6">'+n+'</span>'+VNAMES[n]+
      '<span style="float:right;opacity:.55;font-size:12px">'+(n===18?'the witness \u00b7 ':'')+
      (c?c+' world'+(c>1?'s':''):'the walk only')+'</span></button></li>'}
  sheet('the spine','Thirty-three vertebrae',
    '<p style="color:rgba(245,239,230,.66)">The page is read in movement order; the body is in spine order. '+
    'This is the second order \u2014 where in the body you stand. Lit rows are where you are now.</p><ul>'+rows+'</ul>');
  $('shB').querySelectorAll('[data-n]').forEach(function(b){
    b.addEventListener('click',function(){railSheet(+b.dataset.n)})})}

/* ═══ where you are — the zone holding the reading line ═══ */
var zones=[],cur='threshold',curZ=null;
function setWorld(z){
  var id=z.dataset.world,mv=z.dataset.movement||'';
  document.body.style.setProperty('--ac',z.dataset.c||'#C9A84C');
  document.body.dataset.mv=mv||'';
  $('top').classList.toggle('on-light',z.dataset.ground==='light');
  $('top').classList.toggle('on-stone',z.dataset.ground==='stone');
  var tc=document.querySelector('meta[name=theme-color]');
  if(tc)tc.setAttribute('content',z.dataset.ground==='light'?'#F4EEE3'
    :z.dataset.ground==='stone'?'#F8F4EC':'#0B0910');
  /* "II · The Field": on a phone the bar shows the movement's numeral only — the world's own label, just
     below, carries the name (Chat's ruling: no truncation) */
  var lbl=z.dataset.label||BY[id]&&BY[id].nm||'a i strange game',mm=/^([IVX]+) \u00b7 (.+)$/.exec(lbl),wh=$('where');
  wh.textContent='';
  if(mm){var nb=document.createElement('b');nb.className='wmv';nb.textContent=mm[1];
    var nn=document.createElement('span');nn.className='wnm';nn.textContent=' \u00b7 '+mm[2];
    wh.appendChild(nb);wh.appendChild(nn);wh.setAttribute('aria-label',lbl)}
  else{wh.textContent=lbl;wh.removeAttribute('aria-label')}
  /* The count is labelled "world", so it counts WORLDS — filtered against the canon, not
     against the 'between' sentinel. That filter also admitted the threshold, the rose window
     (part of the choir) and the Sky (explicitly outside the worlds set), so the opening screen
     read "01 / 51" directly above a cue saying "forty-eight worlds", and the final world showed
     50 / 51 — the nav always implying there was more to find. The JOURNEY (← →, the arrow keys)
     still travels to the threshold and the Sky: they are places you can go, they are simply not
     worlds. Same read-from-canon discipline as the Door's POOL and the Tab Page's rows. */
  var wn=$('wCount');
  if(wn){var ord=zones.filter(function(q){return BY[q.dataset.world]});
    var at=ord.indexOf(z);
    /* off the walk — at the threshold, the rose window, the Sky — the counter names the
       whole rather than going blank: an empty gap between two arrows says nothing. */
    wn.textContent=(at>=0?('0'+(at+1)).slice(-2):'\u2014')+' / '+ord.length}
  var up=id!=='threshold';
  $('rail').classList.toggle('up',up);$('rail').classList.toggle('gone',!up);
  $('railhit').classList.toggle('gone',!up);
  birth(up);
  var vs=z.dataset.v,setv={};
  if(vs==='all'){for(var n=1;n<=33;n++)setv[n]=1}
  else if(vs)vs.split(',').forEach(function(n){setv[+n]=1});
  railEls.forEach(function(el,i){el.classList.toggle('lit',!!setv[i+1])});
  /* the world gets .seen the first time it arrives — v2's entry choreography, as a mechanism */
  z.classList.add('seen');
  document.body.classList.toggle('pres',z.dataset.ground!=='light');
  /* the Point's behaviour changes with the movement it is in */
  P.state = id==='threshold'?'threshold'
          : id==='sky'?'sky'
          : mv==='VI'?'centre'
          : (mv==='IV'||mv==='IX')?'anchor'
          : 'thread';
  if(mv!=='IV'&&mv!=='IX')ANCH=null;
  var un=$('unsewn');
  if(mv==='VI'){sewFreeze=z.offsetTop;un.style.display='block';
    un.style.top='0';un.style.transform='translateY('+z.offsetTop+'px)';un.style.height=z.offsetHeight+'px';   /* moved, not re-laid-out: no layout shift */
    requestAnimationFrame(function(){un.style.opacity=1})}
  else{sewFreeze=null;un.style.opacity=0;un.style.display='none'}
  sewScroll();
  if(mv==='VIII'&&!P.split){P.split=true;pt2.classList.remove('hid')}
  if(mv!=='VIII'&&P.split){P.split=false;pt2.classList.add('hid')}
  if(window.ASGsound)ASGsound.at(id,mv);
  if(id!==cur){dropMark();cur=id}}
function pickWorld(){
  var line=innerHeight*.45,best=null,bd=1e9;
  for(var i=0;i<zones.length;i++){var z=zones[i],r=z.getBoundingClientRect();
    if(r.bottom<-40||r.top>innerHeight+40)continue;
    var d=(r.top<=line&&r.bottom>=line)?0:Math.min(Math.abs(r.top-line),Math.abs(r.bottom-line));
    if(d<bd){bd=d;best=z}}
  if(best&&best!==curZ){curZ=best;setWorld(best)}}

/* ═══ the blooms — leaving, and coming back ═══ */
function portal(ev,href,col){
  var b=$('bloom');if(!b){location.href=href;return}
  b.style.background=col||getComputedStyle(document.body).getPropertyValue('--ac');
  var cx=50,cy=50;
  if(ev&&ev.clientX){cx=ev.clientX/innerWidth*100;cy=ev.clientY/innerHeight*100}
  b.style.clipPath='circle(0% at '+cx+'% '+cy+'%)';b.style.opacity=1;
  requestAnimationFrame(function(){b.style.clipPath='circle(150% at '+cx+'% '+cy+'%)'});
  if(window.ASGkeys)ASGkeys.depart(cur);   /* C8: asg.departure, one key */
  setTimeout(function(){location.href=href},620)}
/* ↑ from a gateway lands at /#<world> (GATEWAYS.md). Worlds from VI on carry a prefixed id (v-sid),
   so the browser alone finds nothing there: the world's own name resolves here, on load and when the
   hash changes. The page settles its heights while it wakes, so the landing is kept once more on load. */
function hashWorld(){var h=decodeURIComponent(location.hash.slice(1));
  return h&&!document.getElementById(h)?node(h):null}
function land(el){if(!el)return;
  /* hold the landing while the page above still grows (figures mounting, fonts, a slow phone),
     until the reader moves, anything else scrolls the page (a lens keeping its place, the Sky),
     or four seconds pass */
  var moved=false,ours=false,stop=function(){moved=true};
  var go=function(){var m=parseFloat(getComputedStyle(el).scrollMarginTop)||0;   /* the rest point clears the top bar */
    if(Math.abs(el.getBoundingClientRect().top-m)>8){ours=true;el.scrollIntoView({block:'start',behavior:'instant'})}};
  go();
  ['wheel','touchstart','keydown','mousedown'].forEach(function(t){addEventListener(t,stop,{once:true,passive:true})});
  addEventListener('scroll',function(){if(ours){ours=false;return}moved=true},{passive:true});
  var keep=function(){if(!moved)go()};
  var ro=window.ResizeObserver?new ResizeObserver(keep):null;if(ro)ro.observe(document.body);
  addEventListener('load',keep,{once:true});
  setTimeout(function(){if(ro)ro.disconnect()},4000)}
addEventListener('hashchange',function(){var el=hashWorld();if(el)el.scrollIntoView({block:'start'})});
function returnBloom(){
  try{var hw=hashWorld();if(hw){land(hw);return}
    var d=window.ASGkeys&&ASGkeys.departure();
    if(d&&d.world&&Date.now()-d.at<45*60*1000&&!location.hash){land(node(d.world))}}catch(e){}}

/* ═══ the sky — the spine, seen whole ═══ */
/* The map is drawn from its own measured box, so it cannot be drawn before it has one.
   This watches it and draws the first time it reports a size — the same shape as sew()'s
   ResizeObserver on main. Once drawn, the observer lets go. */
function skyRetry(){
  var m=document.getElementById('skymap');
  if(!m||skyRetry.armed)return;
  skyRetry.armed=true;
  function attempt(){
    if(!m.clientWidth||!m.clientHeight)return false;
    if(m.children.length)return true;
    drawSky();
    if(m.children.length){
      document.documentElement.removeAttribute('data-sky-fail');
      return true}
    return false}
  if('ResizeObserver' in window){
    var ro=new ResizeObserver(function(){if(attempt())ro.disconnect()});
    ro.observe(m)}
  addEventListener('load',attempt);
  setTimeout(attempt,400);setTimeout(attempt,1400);
}
function drawSky(){
  /* sky.js owns the pulled-out view; this stays as the fallback if it isn't loaded */
  if(window.ASGsky&&ASGsky.draw){
    try{if(ASGsky.draw({worlds:WORLDS,bands:BANDS,vlist:vlist,vnames:VNAMES,vcol:VCOL,
      sheet:sheet,railSheet:railSheet,goTo:goTo,readable:readable,register:REG}))return;
      /* draw() returns false when the map has no resolved box yet. That used to be silent
         and terminal: boot() called this once, before layout, and nothing ever retried —
         so the Sky was an empty 620×464 void on every normal load. Say so, and retry. */
      document.documentElement.setAttribute('data-sky-fail','no box at draw time');
      skyRetry();return}
    catch(e){document.documentElement.setAttribute('data-sky-fail',String(e&&e.message||e));
      if(window.console)console.error('[sky]',e)}}
  return;   /* the old svg fallback is gone: wave 09 made #skymap a <div>, so it was dead code */
  /* eslint-disable no-unreachable */
  var sv=$('skymap');if(!sv||sv.tagName.toLowerCase()!=='svg')return;
  /* labels at the left edge · the bands and the spanning lines beside them ·
     the spine · the world-lights to the right of it */
  var W=400,H=640,top=26,bot=H-26,dy=(bot-top)/32,cx=164,s='';
  function Y(n){return top+(n-1)*dy}
  var spanN=0;
  WORLDS.forEach(function(w){if(w[3]==='all'){spanN++;
    var x=142-spanN*8;
    s+='<line class="span" x1="'+x+'" y1="'+top+'" x2="'+x+'" y2="'+bot+'"/>'}});
  var bandN=0;
  WORLDS.forEach(function(w){var b=BANDS[w[3]];
    if(b&&w[3]!=='all'&&w[3]!=='R'){bandN++;
      var x=150-bandN*7;
      s+='<line class="band" stroke="'+w[4]+'" x1="'+x+'" y1="'+Y(b[0])+'" x2="'+x+'" y2="'+Y(b[1])+'"/>'}});
  s+='<line class="sp" x1="'+cx+'" y1="'+top+'" x2="'+cx+'" y2="'+bot+'"/>';
  for(var n=1;n<=33;n++){
    s+='<line class="tk" x1="'+(cx-6)+'" y1="'+Y(n)+'" x2="'+(cx+6)+'" y2="'+Y(n)+'"/>';
    if(n===18)s+='<circle class="r18" cx="'+cx+'" cy="'+Y(n)+'" r="5.4"/>';
    var key=(n===1||n===9||n===18||n===20||n===31||n===33);
    s+='<text class="'+(key?'':'vn')+'" x="42" y="'+(Y(n)+3)+'" text-anchor="end">'+n+
       (key?' '+VNAMES[n]:'')+'</text>'}
  var seen={};
  WORLDS.forEach(function(w){
    var vs=vlist(w[3]),n=vs.length?vs[0]:1;
    if(w[3]==='all')n=17;
    var k=seen[n]=(seen[n]||0)+1,x=cx+14+((k-1)%7)*15,yo=((k-1)/7|0)*7;
    s+='<g class="lt" data-id="'+w[0]+'" data-nm="'+w[1]+'" data-in="'+(w[5]?1:0)+'">'+
       '<circle cx="'+x.toFixed(1)+'" cy="'+(Y(n)+yo).toFixed(1)+'" r="'+(w[5]?3.6:2.4)+'" fill="'+w[4]+
       '" opacity="'+(w[5]?.95:.5)+'"/><circle cx="'+x.toFixed(1)+'" cy="'+(Y(n)+yo).toFixed(1)+
       '" r="13" fill="transparent"/></g>'});
  sv.setAttribute('viewBox','0 0 '+W+' '+H);sv.innerHTML=s;
  sv.querySelectorAll('.lt').forEach(function(g){g.addEventListener('click',function(){
    if(g.dataset.in==='1'){goTo(g.dataset.id);closeSheet()}
    else sheet('still to come',g.dataset.nm,
      '<p>Standing at its vertebra, specified and positioned. It arrives with its movement.</p>')})});
  var line=$('skyLine');
  if(line){var built=WORLDS.filter(function(w){return w[5]}).length,pages=REG.entries.length;
    line.innerHTML=WORLDS.length+' worlds on thirty-three vertebrae \u2014 '+built+' built on this page so far. '+
      (pages?pages+' pages in the register behind them, every one a star. ':'')+
      'Nine vertebrae have no world of their own yet \u2014 12, 14, 17, 19, 20, 21, 22, 23, 25 \u2014 '+
      'and the walk passes through all of them: room, not gaps.'}}

/* ═══ boot ═══ */
function boot(){
  strand=$('strand');stitch=strand&&strand.querySelector('svg');
  pt=$('point');pt2=$('point2');ily=$('iloveyou');
  marks=[].slice.call(document.querySelectorAll('.pmark'));
  railEls=[].slice.call($('rail').querySelectorAll('i'));
  zones=[].slice.call(document.querySelectorAll('[data-world]'));
  pt.classList.add('hid','tap');
  pt.addEventListener('click',function(){roll(cur)});
  loop(document.body,pointStep,pointStep);
  loop(document.body,function(){ASGlens.scrollModel()});
  /* cursor presence — a soft light that follows the hand in dark worlds (desktop) */
  var pres=$('presence');
  if(pres&&matchMedia('(pointer:fine)').matches&&!reduced){
    var px=-999,py=-999,tx=-999,ty=-999;
    document.addEventListener('mousemove',function(e){tx=e.clientX;ty=e.clientY;kick()},{passive:true});
    loop(document.body,function(){px+=(tx-px)*.12;py+=(ty-py)*.12;
      pres.style.transform='translate('+px+'px,'+py+'px)'})}
  /* ↓ more below — shown once, and gone the moment the reader moves. Its TEXT is set by the
     register sweep near the end of this file (one place spells every count); this only
     governs when it appears. Setting the text here too was a duplicate that ran later and
     won with digits. */
  var more=$('more');
  if(more){
    var t=setTimeout(function(){if(!scrollY)more.classList.add('on')},1800);
    addEventListener('scroll',function(){clearTimeout(t);more.classList.remove('on')},{once:true,passive:true})}
  /* the hand-drawn line boils */
  var inkT=$('inkT'),bt=0;
  if(inkT)loop(document.body,function(t){if(!ASGlens.get().boil||reduced)return;
    if(t-bt<110)return;bt=t;inkT.setAttribute('seed',String(1+((t/110)|0)%9))});
  /* the rail: one full-height target on a thumb, thirty-three under a cursor */
  var hit=$('railhit'),coarse=matchMedia('(pointer:coarse)').matches;
  if(coarse){var b=document.createElement('button');b.type='button';b.style.flex='1 1 auto';
    b.setAttribute('aria-label','The spine \u2014 thirty-three vertebrae');
    b.addEventListener('click',spineSheet);hit.appendChild(b)}
  else for(var n=1;n<=33;n++){(function(n){var b=document.createElement('button');b.type='button';
    b.setAttribute('aria-label','Vertebra '+n+' \u2014 '+VNAMES[n]);
    b.addEventListener('click',function(){railSheet(n)});hit.appendChild(b)})(n)}
  $('sheetX').addEventListener('click',closeSheet);
  addEventListener('keydown',function(e){if(e.key==='Escape')closeSheet()});
  /* the die: the dot of the i travels to the ring, then the field chooses (v2's best moment) */
  var d=$('die');
  if(d)d.addEventListener('click',function(){
    if(P.state!=='threshold'||P.born||reduced){roll(cur);d.classList.add('filled');return}
    ANCH=d;birth(true);P.state='anchor';
    setTimeout(function(){d.classList.add('filled');roll(cur);
      setTimeout(function(){P.state='threshold';ANCH=null;birth(false)},700)},980)});
  /* the lens control */
  var lb=$('lensBtn');
  if(lb)lb.addEventListener('click',function(){
    sheet('the lens','Four ways of seeing one site',
      '<ul>'+ASGlens.order.map(function(k){var L=ASGlens.all[k];
        return '<li><button type="button" data-lens="'+k+'"><b style="font-weight:500">'+L.nm+
          '</b> \u2014 <i style="font-family:Lora,serif;opacity:.82">'+L.state+'</i></button></li>'}).join('')+
      '</ul><p style="margin-top:12px">Switching keeps you exactly where you are \u2014 same world, same place '+
      'in it. Only the seeing changes. Remembered on this phone once you choose one here, and '+
      '<span style="font-family:ui-monospace,monospace">?lens=</span> works in any URL.</p>');
    $('shB').querySelectorAll('[data-lens]').forEach(function(b){b.addEventListener('click',function(){
      ASGlens.set(b.dataset.lens,true);drawRail();closeSheet()})})});
  var sb=$('sndBtn');
  if(sb)sb.addEventListener('click',function(){
    var nowOn=ASGsound.toggle();
    sb.setAttribute('aria-pressed',nowOn?'true':'false');
    sb.setAttribute('aria-label','Sound \u2014 '+(nowOn?'on':'off'));
    if(nowOn&&curZ)ASGsound.at(curZ.dataset.world,curZ.dataset.movement);
    var w=curZ&&curZ.dataset.world,says=nowOn&&w&&ASGsound.says(w);
    sheet('sound',nowOn?'On':'Off',
      nowOn
        ? '<p>'+(says||'The bed of this movement, and this world\u2019s own voice.')+'</p>'+
          '<p style="color:rgba(245,239,230,.66)">At most two voices sound at once \u2014 a bed and '+
          'a voice. Every centre resolves to one note, and the site names that note in exactly one '+
          'place: the ninth panel of the Tree.</p>'+
          '<p style="color:rgba(245,239,230,.52);font-size:13px">Two worlds are binaural \u2014 the '+
          'Bindu Field and the Axis. Without headphones they collapse to a centred tone, which is '+
          'not a lesser version of them.</p>'
        : '<p>Silent. Nothing was playing before you touched this, and nothing was loaded \u2014 the '+
          'engine does not exist until you ask for it.</p>'+
          '<p style="color:rgba(245,239,230,.66)">Touch it again and the score begins where you '+
          'are standing.</p>')});

  [].forEach.call(document.querySelectorAll('[data-cst]'),function(b){b.addEventListener('click',cstOpen)});
  var wb=$('whatBtn');
  if(wb)wb.addEventListener('click',function(){
    var z=curZ,w=BY[cur]||{},one=z&&z.dataset.one,tue=z&&z.dataset.tuesday,g=z&&z.dataset.guide;
    sheet('what is this?',w.nm||'a i strange game',
      '<p>'+(one||WORLDS.length+' worlds standing on a thirty-three-vertebra spine. '+
        'One point runs through all of it.')+'</p>'+
      (tue?'<p style="color:rgba(245,239,230,.66)"><b style="font-weight:500">A Tuesday.</b> '+tue+'</p>':'')+
      (g?'<ul><li><a href="'+g+'">its guide page \u2192</a></li></ul>'
        :'<p style="color:rgba(245,239,230,.55);font-size:13px">This world\u2019s guide page is one of the twenty-three still to be written.</p>'))});
  /* every link out blooms from the tap point, in this world's colour.
     A door opens like a door first. data-seed marks a page not yet in the repo:
     Code removes the attribute when the seed lands, and the link simply navigates. */
  document.addEventListener('click',function(e){
    var a=e.target.closest&&e.target.closest('a[href]');if(!a)return;
    var h=a.getAttribute('href');
    if(!h||h.charAt(0)==='#'||a.target==='_blank'||a.dataset.nobloom!==undefined)return;
    e.preventDefault();
    var isDoor=a.classList.contains('door'),wait=isDoor&&!reduced?620:0;
    if(isDoor)a.classList.add('open');
    setTimeout(function(){
      if(a.dataset.seed!==undefined){
        var b=$('bloom');
        if(b&&!reduced){var r=a.getBoundingClientRect();
          var cx=(r.left+r.width/2)/innerWidth*100,cy=(r.top+r.height/2)/innerHeight*100;
          b.style.background=a.dataset.c||'#C9A84C';b.style.opacity=1;
          b.style.clipPath='circle(0% at '+cx+'% '+cy+'%)';
          requestAnimationFrame(function(){b.style.clipPath='circle(150% at '+cx+'% '+cy+'%)'});
          setTimeout(function(){b.style.opacity=0;b.style.clipPath='circle(0% at 50% 50%)'},700)}
        setTimeout(function(){
          sheet(isDoor?'this door opens':'this page is in the seed',
            isDoor?a.querySelector('.dn').textContent:h,
            (isDoor?'<p>'+a.querySelector('.dl').textContent+'</p>':'')+
            '<p style="color:rgba(245,239,230,.66)">Goes to <span style="font-family:ui-monospace,monospace;'+
            'font-size:12.5px">'+h+'</span> — one of the pages waiting on the seed upload. '+
            'All three doors open for everyone: no shiver, no waiting, no essence.</p>');
          a.classList.remove('open')},isDoor?520:120);
        return}
      portal(e,h,a.dataset.c)},wait)});
  /* the desktop world-nav: ← 04 / 10 → between worlds, and the arrow keys (v2) */
  var order=function(){return zones.filter(function(z){
    return z.dataset.world&&z.dataset.world!=='between'})};
  function step(d){
    var o=order(),at=o.indexOf(curZ);if(at<0)at=0;
    var to=o[Math.max(0,Math.min(o.length-1,at+d))];
    if(to&&to!==curZ)to.scrollIntoView({block:'start'})}
  var pv=$('wPrev'),nx=$('wNext');
  if(pv)pv.addEventListener('click',function(){step(-1)});
  if(nx)nx.addEventListener('click',function(){step(1)});
  addEventListener('keydown',function(e){
    if(e.target&&/^(input|textarea|select)$/i.test(e.target.tagName))return;
    if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();step(1)}
    else if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();step(-1)}});
  var sd=$('skyDie');if(sd)sd.addEventListener('click',function(){roll(cur)});
  ASGlens.set(ASGlens.read(),false);
  nowLine();drawRail();ASGfig.mount();oneDoor();drawSky();sew();pickWorld();returnBloom();pump();
  addEventListener('load',oneDoor);
  /* one scroll handler, synchronous: sew, pick the world, and pump every step.
     None of it may wait on requestAnimationFrame — see pump() above. */
  var queued=false;
  addEventListener('scroll',function(){
    if(queued)return;queued=true;
    setTimeout(function(){queued=false;pickWorld();pump()},0)},{passive:true});
  addEventListener('resize',function(){sew();pickWorld();kick()});
  addEventListener('load',function(){sew()});
  setTimeout(sew,600);setTimeout(sew,1800);
  if('ResizeObserver' in window){var m=document.querySelector('main');
    if(m)new ResizeObserver(function(){sew()}).observe(m)}}

window.ASG={boot:boot,loop:loop,arriving:arriving,watch:watch,sheet:sheet,close:closeSheet,roll:roll,anchor:anchor,
  loopCount:function(){return LOOPS.length},
  readable:readable,fitc:fitc,portal:portal,register:REG,worlds:WORLDS,by:BY,
  vnames:VNAMES,vcol:VCOL,vlist:vlist,bands:BANDS,sew:sew,drawSky:drawSky,
  onLens:function(){drawRail()},reduced:reduced,
  /* III · the Point speaks: it pulses at every word boundary as text arrives */
  pulse:function(){if(reduced||!pt||!pt.animate)return;
    pt.animate([{boxShadow:'0 0 0 0 rgba(201,168,76,.9)'},{boxShadow:'0 0 0 8px rgba(201,168,76,0)'}],
      {duration:340,easing:'ease-out'})},
  iloveyou:function(col,x,y){
    if(!ily||reduced)return;ily.style.color=col;ily.style.left=(x+12)+'px';ily.style.top=(y-8)+'px';
    ily.classList.add('on');setTimeout(function(){ily.classList.remove('on')},1900)},
  point:P};
window.ASGfig=ASGfig;
})();

/* kit */
