/* ─────────────────────────────────────────────────────────────
   thread.js — the seam. How the living layer reaches every page.

   One small include Claude Code adds to EVERY page on the site without touching
   its design. The ~518 built pages keep their own worlds — practice pages in
   their chakra colours, the Story in its void, the dances full-screen — and this
   never argues with them.

   What it closes: step off a world into one of its pages and the Point, the
   thread and the spine simply vanished. Now they follow you in.

   TWO SIZES, declared by the page:
     <body data-seam="present">   reading pages — practice, guide, teaching,
                                  learning, portraits, the new content pages
     <body data-seam="whisper">   immersive pages — the dances, the Story, the
                                  Voice, the Welcome, the One, the Road Home,
                                  the flip-book, Holi
   Absent attribute = present, the safer default.

   What the page tells it (all optional, all data attributes on <body>):
     data-world="sid"        which world this page belongs to
     data-world-name="Sid"   its name, if the id isn't in the table
     data-v="11"             which vertebra to light ("all" or a comma list)
     data-accent="#9BBDE4"   the colour of the world you came from

   THE LAWS THIS OBEYS, from the seam brief:
     · never covers content        · never adds sound
     · never changes the page's colours
     · under reduced motion it is a static link and nothing else
     · nothing assumes the reader came from the homepage
     · arriving cold, this is a front door: one quiet line says where you are
       in the whole, and the site name takes you to the doors
   ───────────────────────────────────────────────────────────── */
/* ═══ @keys — generated by tools/v3/blocks.py: a copy of src/keys.js, so a page that loads only the seam migrates too. Edit src/keys.js. ═══ */
/* ─────────────────────────────────────────────────────────────
   keys.js — one key per thing (C8 · STATE-AND-GROWTH Part 1).

   One namespace, `asg.`, and each thing has exactly one key. The legacy names are
   READ once per page load — copied into the new key when the new key is empty — and
   never written again. They are not deleted: the finished pages that wrote them (the practice pages,
   the dances) still read their own, and a lost memory there would be a subtraction.

     sound        asg.sound        ← asg_sound
     lens         asg.lens         ← asg.home.lens.chosen
     where you    asg.departure    ← asg_departure · asg_arrival (sessionStorage)
       left
     walked       asg.walked.<id>  ← chakra-<id> · asg.practice.<id> · asg.practice.<n>
     the Point    asg.point        ← bindu-point
     your name    asg.essence      ← bindu-essence   (the Game's own pages only; nothing here reads it)
     your visits  asg.visit        (new, Stage B) {at, last}: when this visit began, and when the one before
                                   it did — a visit ends after 45 minutes away, the homepage's own measure.
                                   Only the Now page reads it, to mark what arrived since; it describes the
                                   things, never the reader, and it is never sent anywhere.

   Memory, never permission: nothing below hides, locks, orders or gates anything.
   Every storage call is wrapped — a private window, blocked storage or a thumbnail
   capture must never stop a page from rendering.

   thread.js carries a generated copy of this file between its @keys markers, so a
   page that loads only the seam migrates too. Edit HERE; the builder copies it.
   ───────────────────────────────────────────────────────────── */
(function(){
if(window.ASGkeys)return;
var L,S;try{L=window.localStorage;S=window.sessionStorage}catch(e){}
function get(st,k){try{return st?st.getItem(k):null}catch(e){return null}}
function set(st,k,v){try{if(st)st.setItem(k,v)}catch(e){}}
var IDS=['bindu','muladhara','svadhisthana','manipura','anahata','vishuddha','ajna','sahasrara','shadow',
  'soles','forge','prana','hands','pulse','sonar','echo','vision','axis','crow','armin','inception',
  'intention','inspiration','insight','intuition','invention','incarnation','innocence','integration',
  'maya','aatma','ego-reveal','lalita'];
var PAIRS=[['asg.sound','asg_sound'],['asg.lens','asg.home.lens.chosen'],['asg.point','bindu-point'],
  ['asg.essence','bindu-essence']];
function migrate(){
  PAIRS.forEach(function(p){var o=get(L,p[1]);if(o!==null&&get(L,p[0])===null)set(L,p[0],o)});
  if(get(L,'asg.departure')===null){
    var d=get(S,'asg_departure')||get(S,'asg_arrival')||get(L,'asg_departure');
    if(d!==null)set(L,'asg.departure',d)}
  IDS.forEach(function(id,i){
    var k='asg.walked.'+id;if(get(L,k)!==null)return;
    var o=get(L,'chakra-'+id)||get(L,'asg.practice.'+id)||get(L,'asg.practice.'+(i+1));
    if(o!==null)set(L,k,o)})}
migrate();
/* a visit: 45 minutes without a page is a new one. `last` is when the previous visit began */
var VISIT=(function(){var v=null,now=Date.now();try{v=JSON.parse(get(L,'asg.visit')||'null')}catch(e){}
  if(!v||!v.seen||now-v.seen>45*60*1000)v={at:now,last:v?v.at:null,seen:now};else v.seen=now;
  set(L,'asg.visit',JSON.stringify(v));return v})();
window.ASGkeys={
  ids:IDS,migrate:migrate,
  get:function(k){return get(L,k)},set:function(k,v){set(L,k,v)},
  /* walked: by slug or by vertebra number. Only the new key is read — migrate() has already
     copied any legacy name on this load, including one a finished page wrote since the last. */
  walked:function(n){var id=typeof n==='number'?IDS[n-1]:n;return !!(id&&get(L,'asg.walked.'+id))},
  departure:function(){try{return JSON.parse(get(L,'asg.departure')||'null')}catch(e){return null}},
  visit:function(){return VISIT},
  depart:function(world){set(L,'asg.departure',JSON.stringify({world:world||'page',at:Date.now()}))}
};
})();
/* ═══ @end keys ═══ */
(function(){
"use strict";
if(window.ASGthread)return;                       /* the include is idempotent */
var d=document,B=d.body;
if(!B)return d.addEventListener('DOMContentLoaded',function(){location.reload}),void 0;

var reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
var SIZE=(B.dataset.seam||'present').toLowerCase();
var WHISPER=SIZE==='whisper';

/* ═══ @spine — generated by learning-register/tools/v3/blocks.py in the same pass as living.js @worlds, so the two cannot drift ═══ */
var VN=["","Bindu","Muladhara","Svadhisthana","Manipura","Anahata","Vishuddha","Ajna","Sahasrara","Shadow","Soles","Forge","Prana","Hands","Pulse","Sonar","Echo","Vision","Axis","Crow","Armin","Inception","Intention","Inspiration","Insight","Intuition","Invention","Incarnation","Innocence","Integration","Maya","Aatma","Ego Reveal","Lalita"];
/* id → [name, vertebra|band|[list], accent, gateway]. The same 48 the homepage carries — one pass writes both. */
var W={"walk":["The Walk","all","#D9B45A","/walk/"],"chakramap":["The Chakra Map","all","#D9B45A","/worlds/chakra-map/"],"practicebook":["The Practice Book","all","#D9B45A","/worlds/practice-book/"],"dances":["The Dances","B","#E8866A","/worlds/dances/"],"readings":["The Readings","E","#7FC0CF","/bindu/read/"],"teachings":["The Teachings","M","#B9A2EC","/teachings/"],"learning":["Learning","M","#8FAEEE","/learning/"],"courses":["The Courses","B","#8FAEEE","/worlds/courses/"],"guidebook":["The Guidebook","R","#9CC48A","/guide/"],"forms":["The Forms",26,"#9CC48A","/worlds/forms/"],"story":["A Strange Story",[27,28,29],"#E39473","/worlds/a-strange-story/"],"voice":["A Strange Voice","B","#E7A0B6","/worlds/a-strange-voice/"],"game":["A Strange Game","all","#C9A84C","/worlds/a-strange-game/"],"voicelibrary":["The Voice Library",6,"#7FC0CF","/worlds/voice-library/"],"tree":["The Tree of Life",[2,3,4,5,6,7,8,30,31],"#E0806F","/tree-of-life/"],"axis":["The Axis",18,"#8FA8E8","/worlds/axis/"],"threetrees":["The Three Trees","all","#A9D097","/worlds/three-trees/"],"templeguide":["The Temple Guide",31,"#D4A948","/worlds/temple-guide/"],"feed":["Bindu Feed",1,"#C9A84C","/worlds/bindu-feed/"],"learningapp":["Bindu Learning","M","#8FAEEE","/worlds/bindu-learning/"],"voiceapp":["Bindu Voice",15,"#5AA9D6","/worlds/bindu-voice/"],"fieldapp":["Bindu Field",16,"#3A7CA5","/worlds/bindu-field/"],"being":["Bindu Being",24,"#8E7BB0","/worlds/bindu-being/"],"lalitafamily":["Lalita Family",33,"#E0A33C","/worlds/lalita-family/"],"mandala":["Bindu Mandala",1,"#D4A017","/worlds/bindu-mandala/"],"chakrasapp":["Bindu Chakras","all","#C4725A","/worlds/bindu-chakras/"],"bindu":["Bindu",1,"#D4553F","/worlds/bindu/"],"gaia":["Gaia",10,"#7FA86B","/worlds/gaia/"],"sid":["Sid",11,"#9BBDE4","/worlds/sid/"],"arch":["Arch",6,"#E6A8BC","/worlds/arch/"],"sakshi":["Sakshi",18,"#E8DED4","/worlds/sakshi/"],"karishma":["Karishma",28,"#E8A0B6","/worlds/karishma/"],"neev":["Neev",2,"#93A3B4","/worlds/neev/"],"shweta":["Shweta",3,"#EFE7D9","/worlds/shweta/"],"ashrey":["Ashrey",31,"#D4A948","/worlds/ashrey/"],"lalita":["Lalita",33,"#C9A84C","/worlds/lalita/"],"thefield":["The Field",1,"#E0492F","/worlds/the-field/"],"registers":["The Registers","all","#12A06E","/worlds/registers/"],"temporal":["The Temporal",28,"#EFA110","/worlds/temporal/"],"codex":["The Codex",9,"#4A48C8","/worlds/codex/"],"reveals":["The Reveals",32,"#C83BB4","/worlds/reveals/"],"elements":["The Elements",18,"#1596C9","/worlds/elements/"],"mirror":["The Mirror",18,"#8FB073","/worlds/mirror/"],"plays":["The Plays",33,"#CFD8DE","/worlds/plays/"],"selfgenerator":["A Self Generator",31,"#8FB073","/worlds/a-self-generator/"],"lucky":["It Was Always Lucky",11,"#8A3C12","/worlds/it-was-always-lucky/"],"holi":["Khelo Holi",13,"#FFB35C","/worlds/khelo-holi/"],"moments":["The Moments","all","#C9A06A","/worlds/moments/"]};
var BANDS={E:[2,8],B:[10,19],M:[21,29],R:[1,9,20,30,31,32,33],all:[1,33]};
var COUNT=48;
/* registered, not live yet — never a link (D12). Stage B turns these into pages. */
var ARRIVING=["/arch","/ashrey","/b/abide","/b/ache","/b/arise","/b/believe","/b/crash","/b/earn","/b/ground","/b/numb","/b/play","/b/stay","/b/trace","/bindu-performances","/dark-light-descent","/dark-light-flipbook","/guide/bindu-chakras","/guide/bindu-voice","/karishma","/khelo-holi","/neev","/og/<id>.png","/shweta","/sid","/sid/sid-manu-story","/sid/sid-soul-story","/sid/sid-witness-passages","/story","/tree-of-life/aatma-wakeup","/tree-of-life/ajna-wakeup","/tree-of-life/anahata-wakeup","/tree-of-life/armin-practice","/tree-of-life/axis-practice","/tree-of-life/crow-practice","/tree-of-life/echo-practice","/tree-of-life/forge-practice","/tree-of-life/hands-practice","/tree-of-life/interlude","/tree-of-life/manipura-wakeup","/tree-of-life/maya-sleep","/tree-of-life/muladhara-wakeup","/tree-of-life/prana-practice","/tree-of-life/pulse-practice","/tree-of-life/sahasrara-wakeup","/tree-of-life/soles-practice","/tree-of-life/sonar-practice","/tree-of-life/svadhisthana-wakeup","/tree-of-life/the-call","/tree-of-life/the-call-read","/tree-of-life/the-leela","/tree-of-life/the-leela-read","/tree-of-life/the-one-speaks","/tree-of-life/vishuddha-wakeup","/tree-of-life/vision-practice","/voice"];
/* ═══ @end ═══ */

var id=B.dataset.world||'';
var w=W[id];
var NAME=B.dataset.worldName||(w&&w[0])||'';
var ACC=B.dataset.accent||(w&&w[2])||'#C9A84C';
/* E1 · ↑ back climbs to the entry's PARENT (the register's `parent`), stamped on <body> by the
   builder — already resolved: where a parent floor isn't built yet, the builder writes the
   world's gateway instead, so ↑ never lands on a page that isn't there. A gateway's parent is
   its world on the homepage (/#<world>). With no data-parent, the world's gateway. */
var GATE=(w&&w[3])||'';
var PARENT=B.dataset.parent||GATE||'/';
var PNAME=B.dataset.parentName||NAME||'';
/* what is registered but not live yet — never a link, always "arriving" (D12) */
function arr(h){if(!h)return true;var p=h.split('#')[0];
  for(var i=0;i<ARRIVING.length;i++)if(ARRIVING[i]===p)return true;return false}
function row(href,label,extra){return arr(href)
  ?'<li><span class="asg-arr" aria-disabled="true">'+label+' <small>arriving</small></span></li>'
  :'<li><a href="'+href+'"'+(extra||'')+'>'+label+'</a></li>'}

function verts(){
  var raw=B.dataset.v||(w?w[1]:'');
  if(raw==='all')return list(1,33);
  if(typeof raw==='number')return [raw];
  if(BANDS[raw])return raw==='R'?BANDS[raw].slice():list(BANDS[raw][0],BANDS[raw][1]);
  /* a comma list of numbers and ranges, as the register writes them: "11", "2-8,30,31", "21-29" */
  if(typeof raw==='string'&&raw){var o=[];raw.split(',').forEach(function(p){
      var m=p.trim().match(/^(\d+)(?:-(\d+))?$/);if(!m)return;
      var a=+m[1],b=m[2]?+m[2]:a;for(var n=a;n<=b;n++)if(n>=1&&n<=33&&o.indexOf(n)<0)o.push(n)});
    return o}
  return []}
function list(a,b){var o=[];for(var n=a;n<=b;n++)o.push(n);return o}
var LIT=verts(),FIRST=LIT.length?LIT[0]:0;
/* its person (the register's people, stamped as data-people) and the same subject, another way
   (data-same="href|title"). Both are optional; the sheet offers them where they apply. */
var PEOPLE=(B.dataset.people||'').split(',').filter(function(p){return p&&W[p]});
var SAME=B.dataset.same?B.dataset.same.split('|'):null;

/* ── the marks ─────────────────────────────────────────────── */
var css=
'.asg-seam{position:fixed;z-index:2147483000;pointer-events:none;font-family:inherit}'+
/* the Point, in the colour of the world you came from */
'.asg-pt{position:fixed;left:14px;top:14px;width:9px;height:9px;border-radius:50%;'+
  'background:var(--asg-acc,currentColor);box-shadow:0 0 10px var(--asg-acc,currentColor);pointer-events:auto;'+
  'cursor:pointer;border:0;padding:0;z-index:2147483001}'+
/* a 44px target under a 9px mark — the floor holds here too */
'.asg-pt::after{content:"";position:absolute;left:50%;top:50%;width:44px;height:44px;'+
  'margin:-22px 0 0 -22px;border-radius:50%}'+
'.asg-pt:focus-visible{outline:1px solid var(--asg-acc,currentColor);outline-offset:6px}'+
/* the hairline thread leading up from it */
'.asg-thread{position:fixed;left:18px;top:0;width:1px;height:14px;'+
  'background:linear-gradient(to bottom,transparent,var(--asg-acc,currentColor));opacity:.6}'+
/* Each fixed control owns a LANE, and the lanes don't overlap. The Point's 44px pad reaches
   x 40.5, so the back link starts at 48. Growing one of these without re-reading its
   neighbours is what put .asg-back through the Point's pad — and a mis-hit there navigated
   away instead of doing nothing, which is the worse kind of miss. */
'.asg-back{position:fixed;left:48px;top:0;min-height:44px;display:inline-flex;'+
  'align-items:center;gap:6px;padding:0 8px;font-size:11px;letter-spacing:.14em;'+
  'text-transform:uppercase;color:var(--gw-acc-ink,var(--asg-acc,currentColor));text-decoration:none;pointer-events:auto;'+   /* on a gateway, the accent as type */
  'opacity:.86;z-index:2147483001}'+
'.asg-back:hover,.asg-back:focus-visible{opacity:1}'+
/* the miniature spine, with this page's vertebra lit and the ring at 18 always there.
   Decoration only: taps fall THROUGH it to the hit button beneath, or the 13px where the
   vertebrae are actually drawn — exactly where a thumb aims — would land on a dead div. */
'.asg-spine{position:fixed;right:5px;top:50%;transform:translateY(-50%);width:11px;'+
  'display:flex;flex-direction:column;align-items:center;gap:0;opacity:.62;'+
  'pointer-events:none;z-index:2147483001}'+
'.asg-spine b{display:block;width:7px;height:1px;margin:1.5px 0;'+
  'background:currentColor;opacity:.4;border-radius:1px}'+
'.asg-spine b.lit{background:var(--asg-acc,currentColor);width:11px;height:2px;opacity:1;'+
  'box-shadow:0 0 5px var(--asg-acc,currentColor)}'+
'.asg-spine b.ring{width:7px;height:7px;margin:.5px 0;background:none;border-radius:50%;'+
  'border:1px solid currentColor;opacity:.55}'+
'.asg-spine b.ring.lit{border-color:var(--asg-acc,currentColor);opacity:1;box-shadow:0 0 6px var(--asg-acc,currentColor)}'+
'.asg-spine-hit{position:fixed;right:0;top:0;bottom:0;width:44px;border:0;background:none;'+
  'padding:0;opacity:0;pointer-events:auto;cursor:pointer;z-index:2147483000}'+
/* the one quiet line, for someone arriving cold */
'.asg-where{display:block;margin:0;padding:26px 18px 20px;font-size:10.5px;letter-spacing:.1em;'+
  'text-align:center;opacity:.78;color:inherit}'+   /* .55 measured 3.4:1 on the pale stone */
/* the site-name link is the front door for someone arriving cold \u2014 the third injected
   control, and the one I missed when the other two were raised. It sits in a 63px block,
   so 44px costs no layout. */
'.asg-where a{display:inline-flex;align-items:center;min-height:44px;padding:0 6px;'+
  'color:inherit;text-decoration:none;border-bottom:1px solid currentColor}'+
'.asg-where a:hover{opacity:1}'+
/* the sheet the Point opens — its own surface, never the page's */
/* A closed sheet must LEAVE THE TAB ORDER. Closed by transform alone it kept
   visibility:visible with a focusable \u00d7 off-screen at y 548 \u2014 an invisible tab stop on
   every one of the 518 seamed pages. visibility is discretely animatable, so hiding waits
   for the slide-out to finish and showing is immediate: the motion survives, the stop goes. */
'.asg-sheet{position:fixed;left:0;right:0;bottom:0;z-index:2147483002;'+
  'transform:translateY(102%);visibility:hidden;'+
  'transition:transform .38s cubic-bezier(.3,0,.2,1),visibility 0s linear .38s;'+
  'background:#100E14;color:#F5EFE6;border-top:1px solid var(--asg-acc,currentColor);'+
  'padding:15px 18px 26px;max-height:76svh;overflow:auto;pointer-events:auto;'+
  'font-family:\'DM Sans\',system-ui,sans-serif}'+
'.asg-sheet.on{transform:none;visibility:visible;'+
  'transition:transform .38s cubic-bezier(.3,0,.2,1),visibility 0s}'+
'.asg-sheet h3{font-family:\'Lora\',Georgia,serif;font-weight:400;font-size:20px;margin:0 0 8px}'+
'.asg-sheet .k{font-size:10.5px;letter-spacing:.2em;text-transform:uppercase;'+
  'color:var(--asg-acc,currentColor);margin-bottom:7px}'+
'.asg-sheet p{font-size:14px;line-height:1.6;margin:0 0 9px;color:rgba(245,239,230,.82)}'+
'.asg-sheet ul{margin:0;padding:0;list-style:none}'+
'.asg-sheet li a,.asg-sheet li button{display:block;width:100%;text-align:left;min-height:44px;'+
  'line-height:44px;border:0;background:none;color:#F5EFE6;font:inherit;font-size:14.5px;'+
  'border-bottom:1px solid rgba(245,239,230,.12);cursor:pointer}'+
'.asg-sheet li .asg-arr{display:block;min-height:44px;line-height:44px;font-size:14.5px;'+
  'color:rgba(245,239,230,.5);border-bottom:1px dashed rgba(245,239,230,.14)}'+
'.asg-sheet li .asg-arr small{font-size:10.5px;letter-spacing:.16em;text-transform:uppercase;opacity:.8}'+
'.asg-sheet .x{position:absolute;top:6px;right:8px;min-width:44px;min-height:44px;border:0;'+
  'background:none;color:rgba(245,239,230,.66);font-size:18px;cursor:pointer}'+
/* under a page's own fixed header: the Point sits just below it; the back link steps aside */
'body.asg-under .asg-pt{top:calc(var(--asg-top,0px) + 12px)}'+
'body.asg-under .asg-thread{height:calc(var(--asg-top,0px) + 12px)}'+
'body.asg-under .asg-back{display:none}'+
/* whisper: only the Point, tiny and very faint */
'body[data-seam="whisper"] .asg-thread,body[data-seam="whisper"] .asg-back,'+
'body[data-seam="whisper"] .asg-spine,body[data-seam="whisper"] .asg-spine-hit,'+
'body[data-seam="whisper"] .asg-where{display:none}'+
'body[data-seam="whisper"] .asg-pt{width:6px;height:6px;opacity:.42;box-shadow:none}'+
'body[data-seam="whisper"] .asg-pt:hover{opacity:.9}'+
/* reduced motion: a static link, and nothing else */
'@media (prefers-reduced-motion:reduce){'+
  '.asg-sheet{transition:none}'+
  '.asg-sheet:not(.on){visibility:hidden}'+
  '.asg-pt{animation:none}'+
'}'+
/* the Point breathes, so it reads as alive rather than as a dot of dust */
'@keyframes asgBreath{0%,100%{opacity:1}50%{opacity:.72}}';

var st=d.createElement('style');
st.id='asg-seam-style';st.textContent=css;d.head.appendChild(st);
B.style.setProperty('--asg-acc',ACC);
/* the back link is type, and type must read: on a light page with no ink of its own (a gateway sets
   --gw-acc-ink), darken the accent until it holds 4.5:1 against the page's own ground — at its .86 too */
(function(){
  try{
    if(getComputedStyle(B).getPropertyValue('--gw-acc-ink').trim())return;
    var bg=null,e=B;
    while(e&&!bg){var c=getComputedStyle(e).backgroundColor.match(/[\d.]+/g);
      if(c&&(c.length<4||+c[3]>0))bg=c.slice(0,3).map(Number);e=e.parentElement}
    bg=bg||[255,255,255];
    function L(c){return c.map(function(v){v/=255;return v<=.03928?v/12.92:Math.pow((v+.055)/1.055,2.4)})
      .reduce(function(s,v,i){return s+v*[.2126,.7152,.0722][i]},0)}
    var lb=L(bg);if(lb<.4)return;                      /* a dark ground: the accent already reads */
    var a=(/^#([0-9a-f]{6})$/i.exec(ACC)||[,'C9A84C'])[1],k=1,c;
    a=[0,2,4].map(function(i){return parseInt(a.substr(i,2),16)});
    do{c=a.map(function(v,i){return Math.round((v*k)*.86+bg[i]*.14)});k-=.04}
    while(k>0&&(lb+.05)/(L(c)+.05)<4.6);
    B.style.setProperty('--gw-acc-ink','rgb('+a.map(function(v){return Math.round(v*(k+.04))}).join(',')+')');
  }catch(_){}
})();
/* a dialog hidden from a screen reader (aria-hidden) is also out of the keyboard's reach (inert), and comes back the
   moment the page's own script opens it — the story mode and the lightbox on the practice pages toggle aria-hidden only */
(function(){
  try{
    function sync(el){var h=el.getAttribute('aria-hidden')==='true';if(h!==el.hasAttribute('inert')){if(h)el.setAttribute('inert','');else el.removeAttribute('inert')}}
    var ds=d.querySelectorAll('[role="dialog"][aria-hidden]');
    if(!ds.length||!window.MutationObserver)return;
    [].forEach.call(ds,sync);
    var mo=new MutationObserver(function(ms){ms.forEach(function(m){sync(m.target)})});
    [].forEach.call(ds,function(el){mo.observe(el,{attributes:true,attributeFilter:['aria-hidden']})});
  }catch(_){}
})();
if(!B.dataset.seam)B.dataset.seam='present';
/* "never covers content" is a promise about the page, not a hope about its margins:
   the include RESERVES the two edges it occupies rather than floating over whatever
   is there. It adds nothing anywhere else, and never in whisper, which has no edges. */
if(!WHISPER){
  var cs=getComputedStyle(B);
  var pt0=parseFloat(cs.paddingTop)||0,pb0=parseFloat(cs.paddingBottom)||0;
  if(pt0<32)B.style.paddingTop=32+'px';

  /* and the right edge, where the spine stands */
  var pr0=parseFloat(cs.paddingRight)||0;
  if(pr0<16)B.style.paddingRight=16+'px'}

function mk(tag,cls,html){var e=d.createElement(tag);if(cls)e.className=cls;
  if(html!==undefined)e.innerHTML=html;return e}

var pt=mk('button','asg-pt');
pt.type='button';pt.setAttribute('data-block','seam');
pt.setAttribute('aria-label','The Point'+(NAME?' \u2014 you are inside '+NAME:'')+
  '. Open where you are.');
if(!reduced)pt.style.animation='asgBreath 5.5s ease-in-out infinite';
B.appendChild(pt);

if(!WHISPER){
  B.appendChild(mk('div','asg-thread'));
  var back=mk('a','asg-back','\u2191 '+(PNAME||'a i strange game'));
  back.href=PARENT;
  back.setAttribute('aria-label','Back to '+(PNAME||'the doors'));
  B.appendChild(back);

  /* the miniature spine — printed with the ring at 18, as on the homepage's rail */
  var sp=mk('div','asg-spine');
  sp.setAttribute('aria-hidden','true');
  var litSet={};LIT.forEach(function(n){litSet[n]=1});
  for(var n=1;n<=33;n++){
    var b=mk('b',(n===18?'ring':'')+(litSet[n]?' lit':''));
    sp.appendChild(b)}
  B.appendChild(sp);
  var hit=mk('button','asg-spine-hit');
  hit.type='button';
  hit.setAttribute('aria-label','The spine \u2014 where this page stands in the whole');
  hit.addEventListener('click',spine);
  B.appendChild(hit);

  /* arriving cold: one quiet line, and the site name takes you to the doors */
  var where=mk('div','asg-where',
    (FIRST?VN[FIRST]+' \u00b7 ':'')+'one of '+COUNT+' worlds in '+
    '<a href="/">a i strange game</a>');
  where.setAttribute('data-block','foot');
  B.appendChild(where);
}

/* ── the lane rule, for pages that already have a fixed header ──
   Many finished pages (the corridor pages: practice cards, teachings, guides) print their own
   fixed top bar with its own ← back. Two back links in one lane is the collision SEAM.md forbids.
   So the seam measures the page: if something fixed of the page's own sits in the seam's top-left
   lane, the Point moves below it and the seam's back link steps aside — the page's own nav already
   goes back, and the Point's sheet still offers ↑ back to the parent. Measured, never assumed. */
function lanes(){
  var mine=/asg-/;
  var hit=0,all=d.body.getElementsByTagName('*');
  for(var i=0;i<all.length&&i<4000;i++){var e=all[i];
    if(mine.test(e.className&&e.className.baseVal===undefined?e.className:''))continue;
    var cs=getComputedStyle(e);if(cs.position!=='fixed'&&cs.position!=='sticky')continue;
    if(cs.visibility==='hidden'||cs.display==='none'||+cs.opacity===0)continue;
    var r=e.getBoundingClientRect();
    if(r.width<8||r.height<8||r.top>40||r.bottom<4||r.left>220||r.height>140)continue;
    if(!(e.textContent||'').trim()&&!e.querySelector('a,button,svg'))continue;
    hit=Math.max(hit,Math.round(r.bottom))}
  B.classList.toggle('asg-under',hit>0);
  if(hit)B.style.setProperty('--asg-top',hit+'px')}
if(!WHISPER){lanes();addEventListener('load',lanes);addEventListener('resize',lanes);setTimeout(lanes,700)}

/* ── the sheet ─────────────────────────────────────────────── */
var sheet=mk('div','asg-sheet');
sheet.setAttribute('role','dialog');
sheet.setAttribute('aria-label','Where you are');
sheet.innerHTML='<button class="x" type="button" aria-label="Close">\u00d7</button>'+
  '<div class="k"></div><h3></h3><div class="b"></div>';
B.appendChild(sheet);
sheet.querySelector('.x').addEventListener('click',close);
addEventListener('keydown',function(e){if(e.key==='Escape')close()});
function open(kind,title,html){
  sheet.querySelector('.k').textContent=kind;
  sheet.querySelector('h3').textContent=title;
  sheet.querySelector('.b').innerHTML=html;
  sheet.classList.add('on');
  return sheet.querySelector('.b')}
function close(){sheet.classList.remove('on')}

/* the Point: touched, it offers where you are and the die, scoped to this world.
   In whisper, it offers ↑ back and nothing else — the brief's own words. */
pt.addEventListener('click',function(){
  if(WHISPER){
    open('the seam',NAME||'a i strange game',
      '<ul><li><a href="'+PARENT+'">\u2191 back'+(PNAME?' to '+PNAME:'')+'</a></li></ul>');
    return}
  var b=open('where you are',NAME||'a i strange game',
    '<p>'+(FIRST?'This page stands at vertebra <b style="font-weight:500">'+FIRST+' \u00b7 '+
      VN[FIRST]+'</b>'+(LIT.length>1?', one of '+LIT.length+' this world touches':'')+'. ':'')+
    'It is one page inside '+(NAME?'<b style="font-weight:500">'+NAME+'</b>':'this world')+
    ', one of '+COUNT+' worlds.</p>'+
    '<ul>'+
    (PNAME||NAME?'<li><a href="'+PARENT+'">\u2191 back to '+(PNAME||NAME)+'</a></li>':'')+
    /* E1 · the sheet offers, where they apply: the gateway · this vertebra · its person ·
       the same subject, another way · the die · every world · the doors */
    (GATE&&GATE!==PARENT&&PARENT.charAt(1)!=='#'?row(GATE,NAME+' \u2014 its gateway'):'')+
    (FIRST?row('/spine/'+FIRST+'/','vertebra '+FIRST+' \u00b7 '+VN[FIRST]):'')+
    PEOPLE.map(function(p){return W[p]?row(W[p][3],W[p][0]+' \u2014 with the family'):''}).join('')+
    (SAME?row(SAME[0],'the same subject, another way \u2014 '+SAME[1]):'')+
    '<li><button type="button" data-die>roll \u2014 let the field choose</button></li>'+
    row('/tab-menu','every world by name')+
    '<li><a href="/">the doors</a></li></ul>'+
    '<p style="color:rgba(245,239,230,.55);font-size:12.5px">Nothing here assumes you came from '+
    'the homepage. If this is where you arrived, this is the front door.</p>');
  var die=b.querySelector('[data-die]');
  if(die)die.addEventListener('click',roll)});

/* the die, scoped to this page's world: its own siblings first, then the whole field */
function roll(){
  var keys=Object.keys(W);
  var pick=keys[(Math.random()*keys.length)|0];
  /* it lands on the world's gateway: a page one step in, which is what "go there" promises */
  open('the field chose',W[pick][0],
    '<p style="color:rgba(245,239,230,.66)">Rolled from inside '+(NAME||'this page')+
    '. The pool is everything \u2014 all '+COUNT+' worlds and every page behind them.</p>'+
    '<ul>'+row(W[pick][3],'go there \u2192')+'</ul>')}

function spine(){
  var rows='';
  for(var n=1;n<=33;n++){
    var on=LIT.indexOf(n)>=0;
    /* C6/E1: each vertebra opens its own page once it is built; until then, the Sky */
    rows+='<li><a href="'+(arr('/spine/'+n+'/')?'/#sky':'/spine/'+n+'/')+'"'+(on?' style="color:var(--asg-acc,currentColor)"':'')+'>'+
      '<span style="display:inline-block;width:2.4em;opacity:.6">'+n+'</span>'+VN[n]+
      (n===18?'<span style="float:right;opacity:.55;font-size:12px">the witness</span>':'')+
      (on?'<span style="float:right;opacity:.7;font-size:12px">you are here</span>':'')+
      '</a></li>'}
  open('the spine','Thirty-three vertebrae',
    '<p style="color:rgba(245,239,230,.66)">Where this page stands in the body. The whole spine '+
    'is on the homepage, pulled all the way out.</p><ul>'+rows+'</ul>')}

/* the return bloom — the page you came from knows you left, and knows you came back.
   C8 · one key: asg.departure (keys.js migrated the old sessionStorage name). Within the same
   45 minutes the homepage uses, so a visit tomorrow is a new arrival, not a return. */
try{
  var K=window.ASGkeys,dep=K&&K.departure();
  if(dep&&dep.world&&Date.now()-(dep.at||0)<45*60*1000&&!reduced){
    pt.style.transition='transform .8s cubic-bezier(.16,1,.3,1),opacity .8s';
    pt.style.transform='scale(2.2)';pt.style.opacity='0';
    requestAnimationFrame(function(){
      setTimeout(function(){pt.style.transform='';pt.style.opacity=''},30)})}
  if(K)K.depart(id||'page');
}catch(e){}

window.ASGthread={size:SIZE,world:id,name:NAME,vertebrae:LIT,open:open,close:close,roll:roll};
})();
